# Generated by Django 3.1.5 on 2021-01-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shit',
            old_name='plain_text',
            new_name='my_text',
        ),
    ]
